# Generated by Django 3.1.1 on 2020-09-09 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Wine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.UUIDField(auto_created=True, unique=True)),
                ('brand_name', models.CharField(max_length=100)),
                ('type_name', models.CharField(max_length=100)),
                ('wine_type', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('image_url', models.CharField(max_length=10000)),
                ('description', models.CharField(max_length=10000)),
                ('price', models.CharField(max_length=100)),
                ('wine_year', models.CharField(max_length=100)),
            ],
        ),
    ]
