# Generated by Django 3.1.1 on 2020-09-14 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aroma', '0002_auto_20200909_2235'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wine',
            name='wine_year',
            field=models.CharField(max_length=50),
        ),
    ]
